image: rocker/tidyverse
check-as-cran:  
  script:
    - apt update
    - apt install -y zlib1g-dev libjpeg-dev texlive-full qpdf
    - R -e 'install.packages(c("testthat","seqinr", "rmarkdown", "utils", "knitr", "ggplot2", "stats", "parallel", "future", "doParallel", "foreach", "tidyverse", "dplyr", "reshape2", "Rdpack"))'
    - R -e 'install.packages("BiocManager")'
    - R -e 'BiocManager::install("Biostrings")'
    - R -e 'roxygen2::roxygenise()'
    - R CMD build --compact-vignettes=both .
    - mv drimmR*.tar.gz drimmR.tar.gz
    - R CMD check --as-cran drimmR.tar.gz
  artifacts:
    paths:
      - drimmR.tar.gz
